# Generated by Django 3.1.2 on 2021-11-08 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('professeur', models.CharField(max_length=30)),
                ('professeur_code', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('grade_code', models.IntegerField()),
                ('cours_donne', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('professeur_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsi.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.CharField(max_length=120)),
                ('etudiant_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsi.etudiant')),
                ('question_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epsi.question')),
            ],
        ),
    ]
