# Generated by Django 3.1.2 on 2021-11-08 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epsi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name_plural': 'Answer'},
        ),
        migrations.AlterModelOptions(
            name='etudiant',
            options={'verbose_name_plural': 'Etudiant'},
        ),
        migrations.AlterModelOptions(
            name='professeur',
            options={'verbose_name_plural': 'Professeur'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Question'},
        ),
    ]
