# Generated by Django 3.1.2 on 2021-11-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsi', '0002_auto_20211109_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=10)),
                ('grade_code', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Grade',
            },
        ),
    ]
