# Generated by Django 3.1.2 on 2021-11-10 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epsi', '0003_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='grade_idx',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='epsi.grade'),
        ),
    ]
