# Generated by Django 3.1.2 on 2021-11-10 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epsi', '0004_etudiant_grade_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='grade_idx',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='grade_code',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='professeur_code',
        ),
    ]
