# Generated by Django 3.1.2 on 2021-11-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsi', '0005_auto_20211110_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='grade_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_code',
            field=models.IntegerField(default='1'),
        ),
    ]
