# Generated by Django 3.1.2 on 2021-11-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsi', '0007_remove_professeur_grade_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='grade_code',
            field=models.IntegerField(default=2),
        ),
    ]
