# Generated by Django 3.1.2 on 2021-11-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsi', '0008_professeur_grade_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='grade',
            field=models.CharField(choices=[('B1', '1'), ('B2', '2'), ('B3', '3'), ('I1', '4'), ('I2', '5')], max_length=10),
        ),
    ]
