# Generated by Django 3.1.2 on 2021-11-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsi', '0010_auto_20211110_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='grade',
            field=models.CharField(max_length=10),
        ),
    ]
