# Generated by Django 3.1.2 on 2021-11-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsi', '0014_auto_20211110_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='grade_code',
            field=models.IntegerField(),
        ),
    ]
