# Generated by Django 3.1.2 on 2021-11-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsi', '0016_auto_20211110_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='grade',
            field=models.CharField(choices=[('1', 'B1'), ('2', 'B2'), ('3', 'B3'), ('4', 'I1'), ('5', 'I2')], max_length=10),
        ),
    ]
