# Generated by Django 3.1.2 on 2021-11-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsi', '0018_auto_20211110_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='grade',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='grade_code',
            field=models.IntegerField(null=True),
        ),
    ]
