# Generated by Django 3.1.2 on 2021-11-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsi', '0021_auto_20211128_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='idx',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
